version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventflow-app
    restart: always
    env_file:
      - .env
    command: ['node', 'dist/shared/infra/http/server.js']
    stop_grace_period: 60s
    stop_signal: SIGTERM
    ports:
      - '3000:3000'
    depends_on:
      redis:
        condition: service_healthy

  workers:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventflow-worker
    restart: always
    env_file:
      - .env
    command: ['node', 'dist/shared/infra/queue/queue-bootstrap.js']
    stop_grace_period: 60s
    stop_signal: SIGTERM
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: eventflow-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  redis-data:
