enum PaymentStatus {
  PENDING = 'PENDING',
  REQUIRES_ACTION = 'REQUIRES_ACTION',
  PROCESSING = 'PROCESSING',
  AUTHORIZED = 'AUTHORIZED',
  PAID = 'PAID',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  DISPUTED = 'DISPUTED',
  UNDER_DISPUTE = 'UNDER_DISPUTE',
  REDEEMED = 'REDEEMED',
  APPROVED = 'APPROVED',
  FAILED = 'FAILED',
}
export { PaymentStatus };
